version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - back-tier 
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  redisdb:
    image: redis
    networks:
      - back-tier 
    ports:
      - "6379:6379"

  webserver:
    build: .
    ports:
      - "8080:3000"
    networks:
      - front-tier
      - back-tier
    links:
      - mongodb
      - redisdb
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - REDIS_HOST=redisdb
networks:
  back-tier:
    driver: bridge 
  front-tier:
    driver: bridge
volumes:
  db: